### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chandrawi**
Hallo,

I like this library and used it to my Arduino projects. I made ADS1x15 python library for used with Raspberry pi or other Linux SBC.
I updated README and put the python library link. I also update some part in README and add some links to example files. Hope you like it!

Regards,
Chandra Wijaya

### CODE REVIEW

**Comment by RobTillaart** [comment]
Being "copied" is a great honor and I will merge it right away. 
(will not make a release for it)

**Comment by RobTillaart** [comment]
@chandrawi 

Merged too fast, you have add much more in it than just a link, including not relevant information.
Please prepare a new correct readme.

Thanks

**Comment by RobTillaart** [comment]
```
### Using Git

To using latest update of the library, you can clone this repository in Arduino library folder. Default library folder for windows is **C:\Users\{username}\Documents\Arduino** and for linux is **~/Documents/Arduino/libraries/**. 
```

This information is **not** relevant to have in the readme.md as all my libraries can be updated and downloaded with the Arduino library manager.

**Comment by RobTillaart** [comment]
Done

**Comment by chandrawi** [comment]
Ok, I understand. Thanks for accepting pull request.

**Comment by RobTillaart** [comment]
Thank you, there were plenty valuable improvements.

**Pull request merged**
